### ISSUE TITLE
Problem Set Stairs Ambiguity

### ISSUE THREAD

**Issue by dkruszew** [anasm-17/DSA_collaborative_prep#6]
For the stairs problem I struggled with my solution for a while until I realized that the stairs function was actually supposed output the symbol "#" and not a numeric character. My original understanding of the problem statement was that you wanted # to represent N i.e, for N = 3, the output should be: ["3--", "33-", "333"], and for N = 2: ["2-", "22"], etc. Perhaps clarify in the problem statement that the output is the specifically the "#" symbol since this symbol is commonly understood as a placeholder for a number.

**Comment by anasm-17** [comment]
Thanks Derek, I'll modify it!
